language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python setup.py test
deploy:
  provider: pypi
  user:
    secure: L3bOocVhMBmoqj8b0vRtDbFRp2ZVvjlrY2fpEUlj7lxmev8JBuaFSZbzyzrTrA3RSE0yWDqkiEXu8V7kifmEpRA1NVp78YcKxbvldkme59AtMrzesUTBfe+x5jrjSXxhgxzevICfC3DFxaIFwwS+uPeoALuRaKL7zCHpEHRLEZSEzIyis6EhyA2Zk7yL/ukaTBSxTHdLQGbrVI+xilki1Odt+/E93cAbrjY5v2DraHl59B8bXksBSUw+ow9AniqIfqYjb+oGdcgDhQB9SpwA+bduvdx6jck5+w4xVxK4tV1sjk8ZHFB+OQfrshNS3C+6rTxepqiTyA/i+xVga4JBlR0Pvnd8IWsQQxrTsaLaYXqVZc0ZE8LecTWWUuCLam2erp+tbbMz2dwRCAM6f4Gm1o89mc/4BPpIdJ2htmwBblvkOy1ZLyjA289584JuIrKvpcPFoWKyrKCIGelqkggi4KPNyzdV6tUL1kwyPvJkfhIH0YxkI/fwDhZ48MLQdrPxusYcU8/ruDNKs9i9TGqQ3eNKSVS4J/aCc5Ot4E7Qr8mytw1I5tqRCWzVqUENK0FMZ0AM15gIiHBpJDdn/ADbNOqjGcqMyOHkf4EZINNgS9oOTQ+oUebC0UnxGggv0CNVwKR9QjmpHz6mlorYgUhPG3IWmQ6ELGG872pfgJE0Qsw=
  password:
    secure: KGrfGMe+TTbtCdld0xoLlSHRYik66OORu5znPXgR5v/Gtj6rI4h/jMhxm+3q8bHfXGlq6qfq62KbHa8Bk99wfIeNMboYDrfvEo7tfXY8AGI/ECzWZwMAS1kiatVOx+Eczgy64IMNUTNBmjuzlhGSydElB70c2PO/Zw6pwy1A45eKk19jtzuiA4lurpy+VhSW4sxW6E21ofqrR3PMKxJWwP8RLnBcLtFH4fr/Y9afVhGt1x/6qaXkUu5suoeWMKS2LRKjVq5gUcbBk6p5scuSLZSDg11WiqkBPq5i0vcX0+9JclClgFhbU+pjVkAPUVxVF4SE02ItwQrWr9562xfXFTag009EhIUmIGycHrcOuKyULGQ/6wC3sAjS15rNPa0vtC01o8FVLcd1IbzFRyvYt7Ky9GSVJlj28b0fq1rsTr0vZh4s25YreT8VomKuY38lRgLk/3rOMen/KdhdKQl0O9j5Y426q9VRzkVRFOYTmP6p2Qp7nYSNE7iMx9unBitYK3Nof2tcwjT1kUv3lLMpVE4sgS/TAIUZh1ZGJk9jClx4Qw7u6AxG12uUZLHvJrp9aJOFp6vdQsp+NSnBkV4IWxNs8ghTP6dng30TawHMe7yxeXQBfn/FKJTdB3UbEmPqku0bY//DhLUV4w/V/IIarBRcW4+ZKrCKzmFoJ9Z469k=
  distributions: "sdist bdist_wheel bdist_egg"
  on:
    repo: ushahidi/deployment-director
    tags: true
